version: '3'
services:
  frontend:
    build: ./frontend
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /home/cmiv/Documents/code_prod/dev/fullstack-ts-boilerplate/frontend
    volumes:
      - ./frontend:/home/cmiv/Documents/code_prod/dev/fullstack-ts-boilerplate/frontend:cached
      - /home/cmiv/Documents/code_prod/dev/fullstack-ts-boilerplate/frontend/node_modules
  api:
    build: ./api
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=7000
    ports:
      - '7000:7000'
    working_dir: /home/cmiv/Documents/code_prod/dev/fullstack-ts-boilerplate/api
    volumes:
      - ./api:/home/cmiv/Documents/code_prod/dev/fullstack-ts-boilerplate/api:cached
      - /home/cmiv/Documents/code_prod/dev/fullstack-ts-boilerplate/api/node_modules
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080