version: '3'
services:
  frontend:
    build: ./frontend
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /root/frontend
    volumes:
      - ./frontend:/root/frontend:cached
  api:
    build: ./api
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /root/api
    volumes:
      - ./api:/root/api:cached
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080